# Original source
# https://docs.cloud.google.com/composer/docs/composer-3/dag-cicd-github

steps:
  - name: python:3.11-slim
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']

  - name: python:3.11-slim
    entrypoint: python3.11
    args: ['-m', 'pytest', '-s', 'dags/']

options:
  logging: CLOUD_LOGGING_ONLY
